# -*- coding: utf-8 -*-
"""A1_Grupo1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16AV4SH2HSAcA_YGhVDQCWGBKdkWFMtmc

# Integrantes do Grupo 1

#### Enzo Neves
#### Gabriel Alberto
#### Gabriela Beatriz
#### Pedro Artur
#### Sabrina Menezes

## Tarefa 1: Importe os dados para este notebook e Gere as Estatísticas descritivas da variável dependente e da variável explicativa
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import statsmodels.formula.api as smf

url = 'https://raw.githubusercontent.com/Gatriz/Base-Dados-2024/b5166a3bfabff18ddc02670ec720dcc601a3f769/base2024.csv'
dados = pd.read_csv(url, encoding = 'latin-1', delimiter=';')
dados.head()

CAR = dados['CAR']
ROE = dados['ROE']
dados2 = pd.DataFrame({'CAR' : CAR, 'ROE':ROE})
dados2.head()

dados2.describe()

plt.figure(1)
plt.plot(dados2['CAR'], label='CAR')
plt.plot(dados2['ROE'], label='ROE')
plt.xlabel('Nº Observações')
plt.ylabel('Variação')
plt.title('Gráfico dos Retornos')
plt.grid(True)
plt.legend()
plt.show()

"""## Tarefa 2: Apresente o diagrama de dispersão entre X e Y."""

plt.figure(2)
plt.scatter(dados2['CAR'], dados2['ROE'])
plt.xlabel('CAR')
plt.ylabel('ROE')
plt.title('Gráfico de Dispersão')
plt.grid(True)
plt.show()

"""## Tarefa 3: Estime o modelo linear $y = \alpha + \beta x + u$ e apresente os resultados na saída padrão do _Statsmodels_ no Python"""

formula = 'ROE ~ CAR'
results = smf.ols(formula, dados2).fit()
print(results.summary())